spring.application.name=merchant-mode

spring.datasource.url=jdbc:postgresql://postgres:5432/merchant_mode_db
shared.datasource.shared.url=jdbc:postgresql://postgres:5432/shared_db

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/ecommerce