spring.application.name=merchant-mode

#Local Database
spring.datasource.local.url=jdbc:postgresql://postgres:5432/merchant_mode_db
spring.datasource.local.username=merchantlocal
spring.datasource.local.password=merchantlocal1234
spring.datasource.local.driver-class-name=org.postgresql.Driver

#Shared Database
spring.datasource.shared.url=jdbc:postgresql://postgres:5432/shared_db
spring.datasource.shared.username=shared
spring.datasource.shared.password=shared1234
spring.datasource.shared.driver-class-name=org.postgresql.Driver

#KeyCloak Database
spring.datasource.keycloak.url=jdbc:postgresql://postgres:5432/keycloak_db
spring.datasource.keycloak.username=keycloak
spring.datasource.keycloak.password=keycloak1234
spring.datasource.keycloak.driver-class-name=org.postgresql.Driver

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/ecommerce