spring.application.name=user-mode

#Local Database
spring.datasource.local.url=jdbc:postgresql://postgres:5432/user_mode_db
spring.datasource.local.username=local
spring.datasource.local.password=local1234

#Shared Database
spring.datasource.shared.url=jdbc:postgresql://postgres:5432/shared_db
spring.datasource.shared.username=shared
spring.datasource.shared.password=shared1234

#KeyCloak Database ( It will only store the account info of user's and merchant's )
spring.datasource.keycloak.url=jdbc:postgresql://postgres:5432/keycloak_db
spring.datasource.keycloak.username=keycloak
spring.datasource.keycloak.password=keycloak1234

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/ecommerce