spring.application.name=user-mode

spring.datasource.url=jdbc:postgresql://postgres:5432/user_mode_db
shared.datasource.url=jdbc:postgresql://postgres:5432/shared_db
keycloak.datasource.url=jdbc:postgresql://postgres:5432/keycloak_db

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/ecommerce